version: "3.8"

services:
  easy_plus:
    # build: .
    image: globevik/sg_life:test
    ports:
      - 3000:3000
    # environment:
    #   - DB_HOST=easy-plus.c18m0smooefb.ap-south-1.rds.amazonaws.com
    #   - DB_USER=admin
    #   - DB_PASSWORD=IhoZEYP5HNmej2ggsWeB
    #   - DB_NAME=easy_plus
    #   - DB_PORT=3306

    container_name: "sg_life"
    networks:
      - sg_life
    restart: always
    volumes:
      - /home/sg_life/logs:/logs
networks:
  sg_life:
    name: sg_life